/* Database schema to keep the structure of the entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    name varchar(100),
    date_of_birth date,
    escape_attempts int,
    neutered boolean,
    weight_kg decimal,
);

-- Add a column species of type string to your animals table. Modify your schema.sql file
ALTER TABLE animals
ADD species varchar(255);

-- Create a table named owners with the following columns:
-- id: integer (set it as autoincremented PRIMARY KEY)
-- full_name: string
-- age: integer
CREATE TABLE owners (
    id int NOT NULL,
    full_name varchar(255),
    Age int,
    PRIMARY KEY (ID)
);

-- Create a table named species with the following columns:
-- id: integer (set it as autoincremented PRIMARY KEY)
-- name: string
CREATE TABLE species (
    id int NOT NULL,
    name varchar(255),
    PRIMARY KEY (ID)
);
